### ISSUE TITLE
The application crashes when i click on Edit Birthday

### ISSUE THREAD

**Issue by qbrave1** [procrastimax/BirthdayBuddy#7]
### Expected behavior:
I expected that the application should not be crash when i click on Edit Birthday Option.

### Actual behavior:
After configure the application when i click onEdit Birthdayoption,the application is you can see in bug vieo proprealy.

### How to reproduce:
1.Download the app from play store and open the app.
2.Then click on procrastimax and
3.click on Edit Birthday
4.Then select photo
5.Click on save option
6.Note the Bug.

### information
* App version:v1.1
* os:Android 6.0.1
* Device:samsung J7
### Recording of the bug
https://youtu.be/n1pspvvJvi0
### Logcat:
<pre><code>E/AndroidRuntime(26030): FATAL EXCEPTION: main

E/AndroidRuntime(26030): Process: com.procrastimax.birthdaybuddy, PID: 26030

E/AndroidRuntime(26030): d.b

E/AndroidRuntime(26030): 	at c.b.a.a.l.B(:32)

E/AndroidRuntime(26030): 	at g.onClick(java-style lambda group:3)

E/AndroidRuntime(26030): 	at android.view.View.performClick(View.java:5106)

E/AndroidRuntime(26030): 	at android.view.View$PerformClick.run(View.java:20329)

E/AndroidRuntime(26030): 	at android.os.Handler.handleCallback(Handler.java:739)

E/AndroidRuntime(26030): 	at android.os.Handler.dispatchMessage(Handler.java:95)

E/AndroidRuntime(26030): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime(26030): 	at android.app.ActivityThread.main(ActivityThread.java:5912)

E/AndroidRuntime(26030): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(26030): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime(26030): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime(26030): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)</code></pre>

**Comment by qbrave1** [comment]
@procrastimax feadbck plezzzz

**Comment by procrastimax** [comment]
Sorry, I did not have the time to review it already. I'm currently working on my exams but I'm definitely going to step into this issue in the next weeks.
All I can say now, is that I can't reproduce this bug on my device.

Does this only happen with the standard birthday of procrastimax? Can you edit other persons birthdays?

**Comment by procrastimax** [comment]
OK I tried exactly this on multiple emulators but I can't reproduce this error :/
So I'm not able to fix this at the moment.
