### ISSUE TITLE
Upload the App to FDroid store

### ISSUE THREAD

**Issue by procrastimax** [procrastimax/BirthdayBuddy#9]

**Comment by Poussinou** [comment]
You could start by opening a [RFP](https://gitlab.com/fdroid/rfp/issues).

**Comment by cajeiri** [comment]
This one should be closed now :)

**Comment by cajeiri** [comment]
@procrastimax Bonus suggestion (haven't tested the app yet): If there isn't a night mode, implement one? Thanks for the cool app!

**Comment by procrastimax** [comment]
> @procrastimax Bonus suggestion (haven't tested the app yet): If there isn't a night mode, implement one? Thanks for the cool app!

see: #16 ;)

**Comment by cajeiri** [comment]
Awesome, missed that one, then I suggest you add an image with dark mode, since some users find that especially important, or add it to the description. Cheers!
